version: 2

models:
  - name: fct_trips
    columns:
      - name: trip_duration_minutes
        tests:
          - not_null
      - name: pu_location_id
        tests:
          - relationships:
              to: ref('stg_taxi_zones')
              field: locationid
  - name: agg_daily_summary
    columns:
      - name: trip_date
        tests:
          - not_null
          - unique